name: PYMES FE Environment
values:
  - key: base_url
    value: 'http://127.0.0.1:5000/api'
  - key: token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
  - key: empresa_id
    value: '1'
color: 0
