name: PYMES FE Environment
values:
  - key: base_url
    value: http://127.0.0.1:5000/api
    enabled: true
  - key: token
    value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
    enabled: true
  - key: empresa_id
    value: "1"
    enabled: true
